# Change these first
owner: SOPORTEAYIGROUP # Your GitHub organization or username, where this repository lives
repo: AYIGROUP # The name of this repository

sites:
  - name: CAOSBI
    url: https://caosbi.ayi-asociados.com/
  - name: CAOS
    url: http://caos.ayi-asociados.com/
  - name: Gitlab Ayigroup
    url: https://gitlab.ayi-asociados.com/
  - name: Ayi Academy
    url: https://ayi.academy/
  - name: Jira Ayigroup
    url: https://jira.ayi-asociados.com/
  - name: Web Corporativa
    url: https://ayi.group/
  - name: Web Inmuta
    url: https://inmuta.com/
  - name: Web Interconomy
    url: https://interconomy.biz/
    
assignees:
  - SOPORTEAYIGROUP

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /AYIGROUP
  logoUrl: https://media-exp1.licdn.com/dms/image/C4D0BAQGV8AwwEyz9mQ/company-logo_200_200/0/1624985757788?e=1652313600&v=beta&t=BoaoRmtQbO6TajDKax3bVFsgSOjfg4hhDgEuVGjZW14
  name: Status AYIGROUP
  introTitle: "**STATUS AYIGROUP** Monitor de uptime y status page."
  introMessage: En caso de caida o degradación de servicio informara automaticamente a Soporte Interno
  navbar:
    - title: Status
      href: https://soporteayigroup.github.io/AYIGROUP/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
